@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Oct 09 23:41:35 +0800 2022
REM SW Build 3173277 on Wed Apr  7 05:07:49 MDT 2021
REM
REM IP Build 3174024 on Wed Apr  7 23:42:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim core_sim_behav -key {Behavioral:sim_1:Functional:core_sim} -tclbatch core_sim.tcl -view C:/Users/LENOVO/Desktop/Exp1/code/sim/core_sim_behav.wcfg -log simulate.log"
call xsim  core_sim_behav -key {Behavioral:sim_1:Functional:core_sim} -tclbatch core_sim.tcl -view C:/Users/LENOVO/Desktop/Exp1/code/sim/core_sim_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
