#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Oct 25 09:15:10 CST 2022
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim core_sim_behav -key {Behavioral:sim_1:Functional:core_sim} -tclbatch core_sim.tcl -view /home/yunfanli/obsidian/ComputerArchitecture/Exp/Exp1/3200102555_Exp1/code/sim/core_sim_behav.wcfg -log simulate.log"
xsim core_sim_behav -key {Behavioral:sim_1:Functional:core_sim} -tclbatch core_sim.tcl -view /home/yunfanli/obsidian/ComputerArchitecture/Exp/Exp1/3200102555_Exp1/code/sim/core_sim_behav.wcfg -log simulate.log

